--- 
abstract: FormFu In Your Model
author: 2007 Copyright (c) Daisuke Maki C<daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-HTML-FormFu
no_index: 
  directory: 
    - inc
    - t
requires: 
  Best: 0
  Catalyst: 0
  Config::Any: 0
  Data::Dumper: 0
  Data::Visitor::Callback: 0
  Digest::MD5: 0
  HTML-FormFu: 0
version: 0.99999
